pipeline {
  agent any
  environment {
    DOCKER_IMAGE = "ruanitro/nextjs-frontend"
    TAG = "1.0"
  }
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Install') {
      steps {
        dir('frontend') {
          bat 'npm install'
        }
      }
    }
    stage('Build') {
      steps {
        dir('frontend') {
          bat 'npm run build'
        }
      }
    }
    stage('Docker Build & Push') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'docker_cred', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_PASSWORD')]) {
          dir('frontend') {
            bat """
              docker build -t %DOCKER_IMAGE%:%TAG% .
              docker login -u %DOCKERHUB_USERNAME% -p %DOCKERHUB_PASSWORD%
              docker push %DOCKER_IMAGE%:%TAG%
              docker logout
            """
          }
        }
      }
    }
  }
}
