version: '3'
services:
  nestjs:
    image: ruanitro/nestjs-backend:1.0
    restart: always
    ports:
      - "3000:3000"
    networks:
      - mysql-net
    environment:
      - DATABASE_URL=mysql://root:root@mysql-master:3306/todolist
    pull_policy: always

  frontend:
    image: ruanitro/nextjs-frontend:1.0
    restart: always
    ports:
      - "3001:3000"       
    networks:
      - mysql-net
    depends_on:
      - nestjs
    environment:
      - NEXT_PUBLIC_API_URL=http://nestjs:3000 

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower_nestjs-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 60
    restart: always

networks:
  mysql-net:
    external: true