services:
  db:
    image: mysql:8.0
    container_name: tododb
    environment:
      MYSQL_ROOT_PASSWORD: "Escola123" 
      MYSQL_DATABASE: "tododb"       
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "3001:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://root:Escola123@db:3306/tododb

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3000

volumes:
  db_data:
