pipeline {
  agent any

  environment {
    DOCKER_IMAGE = "nicolas290/nestjs-backend"
    TAG = "1.0"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install') {
      steps {
        dir('backend') {
          bat 'npm install'
        }
      }
    }

    stage('Build') {
      steps {
        dir('backend') {
          bat 'npm run build'
        }
      }
    }

    stage('Docker Build & Push') {
      steps {
        dir('backend') {
          withCredentials([usernamePassword(
            credentialsId: 'docker_cred', 
            usernameVariable: 'DOCKERHUB_USERNAME', 
            passwordVariable: 'DOCKERHUB_PASSWORD'
          )]) {
            bat """
              docker build -t %DOCKER_IMAGE%:%TAG% .
              docker login -u %DOCKERHUB_USERNAME% -p %DOCKERHUB_PASSWORD%
              docker push %DOCKER_IMAGE%:%TAG%
              docker logout
            """
          }
        }
      }
    }
  }
}
